title: Bron över Rättvik
email: bronoverrattvik@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bron över Rättvik är dessutom lättläst och fängslande: Du behöver
  inte ha någon som helst vana vid att läsa tung vetenskaplig text.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bronoverrattvik
#github_username:  jekyll

# Build settings
theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

google_analytics: UA-152693638-2

minima:
  date_format: "%Y-%m-%d"

facebook_username: bronoverrattvik
github_username: bronoverrattvik
youtube_channel: UCtZqb4bn5vr8e60QblxvHhQ
youtube_channel_name: Bron över Rättvik
show_excerpts: true
