version: '3'
services:
  jekyll:
    image: starefossen/github-pages # stuck at github-pages v202 :/
    command: jekyll serve -d /usr/src/app/_site --watch --force_polling -H 0.0.0.0 -P 4000
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    tty: true
